
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/boj/redistore"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"

[[constraint]]
  name = "github.com/cloudfoundry/loggregatorlib"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  name = "github.com/garyburd/redigo"

[[constraint]]
  name = "github.com/gocraft/web"

[[constraint]]
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/gorilla/context"

[[constraint]]
  name = "github.com/gorilla/csrf"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/gorilla/sessions"

[[constraint]]
  name = "github.com/govau/cf-common"
  version = "0.0.2"

[[constraint]]
  name = "github.com/jordan-wright/email"

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.0.7"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/yvasiyarov/gorelic"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/oauth2"
