---
inherit: manifest-base.yml
applications:
- name: dashboard
  host: dashboard
  instances: 1
  env:
    CONSOLE_HOSTNAME: https://dashboard.system.g.cld.gov.au
    CONSOLE_LOGIN_URL: https://login.system.g.cld.gov.au/
    CONSOLE_UAA_URL: https://uaa.system.g.cld.gov.au/
    CONSOLE_API_URL: https://api.system.g.cld.gov.au/
    CONSOLE_LOG_URL: https://logs.system.g.cld.gov.au/
    CF_SKIN: govau
    SESSION_BACKEND: securecookie
    SESSION_KEY: "I am ignored right now"
