---
buildpack: go_buildpack
memory: 256M
services:
- dashboard-ups
- dashboard-redis
env:
  SECURE_COOKIES: true
  GA_TRACKING_ID: UA-48605964-34
  GOVERSION: go1.9
  GOPACKAGENAME: github.com/18F/cg-dashboard
  SESSION_BACKEND: redis
