---
buildpack: go_buildpack
memory: 256M
services:
- dashboard-ups
- dashboard-redis
env:
  SECURE_COOKIES: true
  GOVERSION: go1.8
  GOPACKAGENAME: github.com/18F/cg-dashboard
  SESSION_BACKEND: redis
